version: '3.8'

services:
  frontend:
    build: ./
    ports:
      - 8080:8080
  backend:
    build: ./src/menu
    volumes:
      - static_volume:/app/
    depends_on:
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adeyinka
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=restaurant

  nginx:
    build: ./src/nginx
    volumes:
      - static_volume:/app/
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: